name: orca_2025
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - ffmpeg=8.0.0
  - openssl=3.6.0
  - pip=25.2
  - python=3.10.12
  - pip:
      - -r requirements.txt
prefix: /opt/miniconda3/envs/orca_2025
